name: Build Pull Request
on: push

jobs:
    test_job:
        name: Assemble
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            users: master

          - name: Assemble Debug
            run: ./gradlew assembleDebug
